andbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  laser_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_joint
    pid: {p: 1, i: 1, d: 1}
  # Velocity Controllers -------------------------------------
  ir_up_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: ir_up_joint
    pid: {p: 1, i: 0, d: 0, i_clamp: 100}

  ir_down_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: ir_down_joint
    pid: {p: 1, i: 0, d: 0, i_clamp: 100}


  # Effort Controllers ---------------------------------------
  leftWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_wheel_hinge
    pid: {p: 20.0, i: 10, d: 10.0}
  rightWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_wheel_hinge
    pid: {p: 20.0, i: 10, d: 10.0}



