obstacle_range: 2.0
raytrace_range: 2.5
footprint: [[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25]] 
#inflation_radius: 1.0
#cost_scaling_factor: 5.0
transform_tolerance : 0.5
observation_sources: point_cloud_sensor
laser_scan_sensor: {sensor_frame: head_joint, data_type: PointCloud, topic: /ir_up_measure, marking: true, clearing: false, expected_update_rate: 150}
